# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import produto_pb2 as produto__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in produto_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProdutoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Produzir = channel.unary_unary(
                '/produto.ProdutoService/Produzir',
                request_serializer=produto__pb2.ProdutoRequest.SerializeToString,
                response_deserializer=produto__pb2.ProdutoResponse.FromString,
                _registered_method=True)
        self.Consumir = channel.unary_unary(
                '/produto.ProdutoService/Consumir',
                request_serializer=produto__pb2.ConsumirRequest.SerializeToString,
                response_deserializer=produto__pb2.ProdutoResponse.FromString,
                _registered_method=True)


class ProdutoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Produzir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Consumir(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProdutoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Produzir': grpc.unary_unary_rpc_method_handler(
                    servicer.Produzir,
                    request_deserializer=produto__pb2.ProdutoRequest.FromString,
                    response_serializer=produto__pb2.ProdutoResponse.SerializeToString,
            ),
            'Consumir': grpc.unary_unary_rpc_method_handler(
                    servicer.Consumir,
                    request_deserializer=produto__pb2.ConsumirRequest.FromString,
                    response_serializer=produto__pb2.ProdutoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'produto.ProdutoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('produto.ProdutoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProdutoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Produzir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/produto.ProdutoService/Produzir',
            produto__pb2.ProdutoRequest.SerializeToString,
            produto__pb2.ProdutoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Consumir(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/produto.ProdutoService/Consumir',
            produto__pb2.ConsumirRequest.SerializeToString,
            produto__pb2.ProdutoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
