# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: produto.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'produto.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rproduto.proto\x12\x07produto\"\x1e\n\x0eProdutoRequest\x12\x0c\n\x04nome\x18\x01 \x01(\t\"$\n\rVenderRequest\x12\x13\n\x0bsolicitante\x18\x01 \x01(\t\"#\n\x0fProdutoResponse\x12\x10\n\x08mensagem\x18\x01 \x01(\t2\x88\x01\n\x0eProdutoService\x12:\n\x05\x41ssar\x12\x17.produto.ProdutoRequest\x1a\x18.produto.ProdutoResponse\x12:\n\x06Vender\x12\x16.produto.VenderRequest\x1a\x18.produto.ProdutoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'produto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUTOREQUEST']._serialized_start=26
  _globals['_PRODUTOREQUEST']._serialized_end=56
  _globals['_VENDERREQUEST']._serialized_start=58
  _globals['_VENDERREQUEST']._serialized_end=94
  _globals['_PRODUTORESPONSE']._serialized_start=96
  _globals['_PRODUTORESPONSE']._serialized_end=131
  _globals['_PRODUTOSERVICE']._serialized_start=134
  _globals['_PRODUTOSERVICE']._serialized_end=270
# @@protoc_insertion_point(module_scope)
